(() => {
'use strict';
const C=window.EV_CONFIG||{}; const DB=window.EV_VEHICLES||[];
const $=id=>document.getElementById(id);
let map,routeLayer,rangeLayer,stations=[],stationMarkers=[],waypointMarkers=[],route=null,selectedCar=null,roundTrip=false,deferredPrompt=null;
let waypoints=[{type:'origin',label:'Origem',address:'',coords:null},{type:'destination',label:'Destino 1',address:'',coords:null}];
let favorites=JSON.parse(localStorage.getItem('evp3_places')||'[]');
let esg=JSON.parse(localStorage.getItem('evp3_esg')||'{"trips":0,"km":0,"savings":0,"co2":0}');
let lastEnergy=null;
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const num=v=>Number(v||0).toLocaleString('pt-BR',{maximumFractionDigits:1});
const safe=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const typeName=t=>(
 {BEV:'100% elétrico',PHEV:'híbrido plug-in',REEV:'REEV / extensor',HEV:'híbrido',MHEV:'híbrido leve'}[t]||t||'não informado');
function toast(msg){const e=$('toast');e.textContent=msg;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2800)}
function init(){
 map=L.map('map').setView([-8.05,-34.88],7); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);
 setupVehicles(); setupWaypoints(); setupButtons(); setupFilters(); setupDefaults(); renderFavorites(); renderESG(); updateFuelBox();
 if('serviceWorker' in navigator && location.protocol!=='file:') navigator.serviceWorker.register('sw.js').catch(()=>{});
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});
 $('installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();deferredPrompt=null;$('installBtn').classList.add('hidden')};
}
function setupDefaults(){const d=new Date();$('departureDate').value=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);$('startBattery').value=localStorage.getItem('evp3_battery')||C.defaults.startBattery;$('startFuel').value=localStorage.getItem('evp3_fuel')||C.defaults.startFuel;$('kwhPrice').value=localStorage.getItem('evp3_kwh')||C.defaults.kwhPrice;$('gasPrice').value=localStorage.getItem('evp3_gas')||C.defaults.gasPrice;$('ethanolPrice').value=localStorage.getItem('evp3_ethanol')||C.defaults.ethanolPrice;['startBattery','startFuel','kwhPrice','gasPrice','ethanolPrice'].forEach(id=>$(id).addEventListener('change',saveSettings));}
function saveSettings(){localStorage.setItem('evp3_battery',$('startBattery').value);localStorage.setItem('evp3_fuel',$('startFuel').value);localStorage.setItem('evp3_kwh',$('kwhPrice').value);localStorage.setItem('evp3_gas',$('gasPrice').value);localStorage.setItem('evp3_ethanol',$('ethanolPrice').value);if(route)calculateEnergy()}
function setupVehicles(){const brands=[...new Set(DB.map(x=>x.brand))].sort();$('brandSelect').innerHTML='<option value="">Selecione...</option>'+brands.map(b=>`<option>${safe(b)}</option>`).join('');$('brandSelect').onchange=()=>{const b=$('brandSelect').value;const cars=DB.filter(x=>x.brand===b);$('modelSelect').disabled=!b;$('modelSelect').innerHTML='<option value="">Selecione...</option>'+cars.map((c,i)=>`<option value="${i}">${safe(c.model)}${c.version&&c.version!=='—'?' — '+safe(c.version):''} · ${safe(typeName(c.type))}</option>`).join('');};$('modelSelect').onchange=()=>{const b=$('brandSelect').value;selectedCar=DB.filter(x=>x.brand===b)[Number($('modelSelect').value)];updateCarUI();};const fav=JSON.parse(localStorage.getItem('evp3_car')||'null');if(fav){const idx=brands.indexOf(fav.brand);if(idx>=0){$('brandSelect').value=fav.brand;$('brandSelect').dispatchEvent(new Event('change'));const cars=DB.filter(x=>x.brand===fav.brand);const ci=cars.findIndex(x=>x.model===fav.model&&x.version===fav.version);$('modelSelect').value=String(ci>=0?ci:0);$('modelSelect').dispatchEvent(new Event('change'));return}}$('brandSelect').value=brands.includes('Leapmotor')?'Leapmotor':brands[0];$('brandSelect').dispatchEvent(new Event('change'));$('modelSelect').value='0';$('modelSelect').dispatchEvent(new Event('change'));}
function updateCarUI(){if(!selectedCar)return;const estimated=!selectedCar.consumption&&selectedCar.battery&&selectedCar.range;const consumption=selectedCar.consumption||(estimated?selectedCar.battery/selectedCar.range*100:null);selectedCar._calcConsumption=consumption;const specs=[['Propulsão',typeName(selectedCar.type)],['Bateria',selectedCar.battery?num(selectedCar.battery)+' kWh':'—'],['Autonomia',selectedCar.range?num(selectedCar.range)+' km':'—'],['Consumo',consumption?num(consumption)+' kWh/100 km':'—'],['Potência',selectedCar.power||'—'],['Tração',selectedCar.traction||'—']];$('carSpecs').innerHTML=specs.map(x=>`<div class="spec"><span>${x[0]}</span><b>${safe(x[1])}</b></div>`).join('');$('dataQuality').textContent=estimated?'⚠️ Consumo estimado pela relação bateria/autonomia; use como referência, não como dado oficial.':'✓ Consumo disponível na base de dados.';updateFuelBox();}
function updateFuelBox(){$('fuelBox').classList.toggle('hidden',!['PHEV','REEV','HEV','MHEV'].includes(selectedCar?.type));}
function setupWaypoints(){renderWaypoints()}
function renderWaypoints(){const box=$('waypoints');box.innerHTML=waypoints.map((w,i)=>`<div class="waypoint" draggable="true" data-index="${i}"><div class="wp-head"><span><span class="drag">☷</span>${safe(w.label)}</span>${i?`<button class="wp-remove" data-remove="${i}">Remover</button>`:''}</div><div class="relative"><input id="wp_${i}" value="${safe(w.address)}" placeholder="Endereço, cidade ou local" autocomplete="off"><div id="res_${i}" class="autocomplete-results hidden"></div></div></div>`).join('');waypoints.forEach((_,i)=>setupAutocomplete(i));box.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{waypoints.splice(Number(b.dataset.remove),1);relabel();renderWaypoints()});let dragIndex=null;box.querySelectorAll('.waypoint').forEach(el=>{el.ondragstart=()=>dragIndex=Number(el.dataset.index);el.ondragover=e=>e.preventDefault();el.ondrop=()=>{const to=Number(el.dataset.index);if(dragIndex===to)return;const [m]=waypoints.splice(dragIndex,1);waypoints.splice(to,0,m);relabel();renderWaypoints()}})}
function relabel(){let d=0,s=0;waypoints.forEach((w,i)=>{if(i===0){w.type='origin';w.label='Origem'}else if(w.type==='stop'){w.label='Parada '+(++s)}else{w.type='destination';w.label='Destino '+(++d)}})}
function setupAutocomplete(i){const input=$('wp_'+i),res=$('res_'+i);let timer;input.oninput=()=>{waypoints[i].address=input.value;waypoints[i].coords=null;clearTimeout(timer);const q=input.value.trim();if(q.length<3){res.classList.add('hidden');return}timer=setTimeout(async()=>{try{const r=await fetch(C.services.geocode+'?q='+encodeURIComponent(q)+'&limit=6');const data=await r.json();res.innerHTML=(data.features||[]).map((f,j)=>{const p=f.properties||{},text=[p.name,p.city||p.town,p.state,p.country].filter(Boolean).join(', ');return `<div class="autocomplete-item" data-j="${j}">📍 ${safe(text)}</div>`}).join('');res.classList.toggle('hidden',!data.features?.length);res.querySelectorAll('.autocomplete-item').forEach((el,j)=>el.onclick=()=>{const f=data.features[j];const p=f.properties||{};const text=[p.name,p.city||p.town,p.state,p.country].filter(Boolean).join(', ');input.value=text;waypoints[i].address=text;waypoints[i].coords=[f.geometry.coordinates[1],f.geometry.coordinates[0]];res.classList.add('hidden');drawWaypoints()})}catch{res.classList.add('hidden')}},C.geocodeDebounce)} }
async function geocode(a){try{const r=await fetch(C.services.geocode+'?q='+encodeURIComponent(a)+'&limit=1');const d=await r.json();const f=d.features?.[0];return f?[f.geometry.coordinates[1],f.geometry.coordinates[0]]:null}catch{return null}}
async function ensureCoords(){for(const w of waypoints){if(w.address&&!w.coords)w.coords=await geocode(w.address)}}
function drawWaypoints(){waypointMarkers.forEach(m=>map.removeLayer(m));waypointMarkers=[];waypoints.forEach(w=>{if(!w.coords)return;const m=L.marker(w.coords).addTo(map).bindPopup(`<b>${safe(w.label)}</b><br>${safe(w.address)}`);waypointMarkers.push(m)})}
function setupButtons(){$('addDestinationBtn').onclick=()=>{waypoints.push({type:'destination',label:'Destino',address:'',coords:null});relabel();renderWaypoints()};$('addStopBtn').onclick=()=>{waypoints.push({type:'stop',label:'Parada',address:'',coords:null});relabel();renderWaypoints()};$('roundTripBtn').onclick=()=>{roundTrip=!roundTrip;$('roundTripBtn').classList.toggle('active',roundTrip);$('roundTripBtn').textContent=roundTrip?'↔ Ida e volta ATIVADA':'↔ Ida e volta'};$('calculateBtn').onclick=calculateTrip;$('homeBtn').onclick=()=>useSavedPlace('home');$('workBtn').onclick=()=>useSavedPlace('work');$('savePlaceBtn').onclick=savePlace;$('favoriteCarBtn').onclick=()=>{if(!selectedCar)return;localStorage.setItem('evp3_car',JSON.stringify(selectedCar));toast('Veículo favorito salvo.')};$('pdfBtn').onclick=exportPDF;$('esgBtn').onclick=()=>{$('esgModal').classList.remove('hidden');renderESG()};$('closeEsg').onclick=()=>{$('esgModal').classList.add('hidden')};$('resetEsg').onclick=()=>{if(confirm('Zerar histórico ESG?')){esg={trips:0,km:0,savings:0,co2:0};persistESG();renderESG()}};$('exportBtn').onclick=exportBackup;$('importBtn').onclick=()=>$('importFile').click();$('importFile').onchange=importBackup;$('copySummaryBtn').onclick=copySummary;$('resetSettingsBtn').onclick=()=>{if(confirm('Restaurar preços e parâmetros padrão?')){localStorage.removeItem('evp3_battery');localStorage.removeItem('evp3_fuel');localStorage.removeItem('evp3_kwh');localStorage.removeItem('evp3_gas');localStorage.removeItem('evp3_ethanol');setupDefaults();toast('Padrões restaurados.')}}}
function useSavedPlace(key){let v=localStorage.getItem('evp3_'+key);if(!v){v=prompt('Informe o endereço de '+(key==='home'?'Casa':'Trabalho')+':');if(!v)return;localStorage.setItem('evp3_'+key,v)}waypoints[0].address=v;waypoints[0].coords=null;renderWaypoints()}
function savePlace(){const a=waypoints[0].address;if(!a){toast('Informe primeiro a origem.');return}const n=prompt('Nome do local:',a);if(!n)return;favorites.push({name:n,address:a});localStorage.setItem('evp3_places',JSON.stringify(favorites));renderFavorites();toast('Local salvo.')}
function renderFavorites(){const s=$('favoritePlaceSelect');s.innerHTML='<option value="">⭐ Locais favoritos</option>'+favorites.map((f,i)=>`<option value="${i}">${safe(f.name)}</option>`).join('');s.classList.toggle('hidden',!favorites.length);s.onchange=()=>{const f=favorites[Number(s.value)];if(!f)return;waypoints[0].address=f.address;waypoints[0].coords=null;renderWaypoints()}}
function setupFilters(){['filterDC','filterAC'].forEach(id=>$(id).onchange=renderStations);$('showRange').onchange=drawRange}
async function calculateTrip(){const btn=$('calculateBtn');btn.disabled=true;btn.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i> Calculando...';try{await ensureCoords();if(waypoints.filter(w=>w.coords).length<2)throw Error('Informe uma origem e pelo menos um destino.');if(roundTrip&&!waypoints.some(w=>w.type==='return')){const o=waypoints[0];waypoints.push({type:'return',label:'Retorno',address:o.address,coords:[...o.coords]})}if(!roundTrip)waypoints=waypoints.filter(w=>w.type!=='return');drawWaypoints();const coords=waypoints.filter(w=>w.coords).map(w=>w.coords[1]+','+w.coords[0]).join(';');const r=await fetch(C.services.route+coords+'?overview=full&geometries=geojson&steps=true');const d=await r.json();if(d.code!=='Ok'||!d.routes?.length)throw Error('Não foi possível calcular a rota.');route=d.routes[0];drawRoute();await calculateEnergy();await loadStations();await loadWeather();saveESG();toast('Viagem calculada com sucesso.')}catch(e){console.error(e);toast(e.message||'Erro ao calcular viagem.')}finally{btn.disabled=false;btn.innerHTML='<i class="fa-solid fa-bolt"></i> Calcular viagem'}}
function drawRoute(){if(routeLayer)map.removeLayer(routeLayer);routeLayer=L.geoJSON(route.geometry,{style:{color:'#34d399',weight:6,opacity:.9}}).addTo(map);map.fitBounds(routeLayer.getBounds(),{padding:[25,25]})}
function factors(){return Number($('driveMode').value)*Number($('acMode').value)*($('rainMode').checked?1.12:1)*($('elevationMode').checked?1.08:1)}
function calculateEnergy(){if(!route||!selectedCar)return;const km=route.distance/1000,c=selectedCar._calcConsumption||selectedCar.consumption||0,f=c*factors(),start=Math.min(100,Math.max(0,Number($('startBattery').value)||0)),cap=Number(selectedCar.battery)||0,kwhPrice=Number($('kwhPrice').value)||0,gasPrice=Number($('gasPrice').value)||0,ethPrice=Number($('ethanolPrice').value)||0;let electricKm=0,fuelKm=0,kwh=0,fuel=0,battery=start;const plug=['BEV','PHEV','REEV'].includes(selectedCar.type);if(selectedCar.type==='BEV'){electricKm=km;kwh=km*f/100;battery=cap?Math.max(0,start-kwh/cap*100):start}else if(selectedCar.type==='PHEV'||selectedCar.type==='REEV'){const er=(selectedCar.range||0)*start/100;electricKm=Math.min(km,er);fuelKm=Math.max(0,km-electricKm);kwh=electricKm*f/100;const kpl=Number(selectedCar.fuelConsumption)||selectedCar.gasKm||18;fuel=fuelKm/kpl;battery=cap?Math.max(0,start-kwh/cap*100):start}else{fuelKm=km;const kpl=Number(selectedCar.gasKm)||15;fuel=km/kpl;battery=100}const evCost=kwh*kwhPrice,gasCost=fuel*gasPrice,ethKm=Number(selectedCar.ethanolKm)||10,ethCost=(fuelKm/ethKm)*ethPrice,total=evCost+(fuelKm?Math.min(gasCost,ethCost):0),gasEquivalent=km/(Number(selectedCar.gasKm)||12)*gasPrice,saving=Math.max(0,gasEquivalent-total);lastEnergy={km,electricKm,fuelKm,kwh,fuel,battery,evCost,gasCost,ethCost,total,saving,f};renderEnergy();drawRange()}
function renderEnergy(){const d=lastEnergy;if(!d)return;$('batteryPercent').textContent=Math.round(d.battery)+'%';$('batteryBar').style.width=Math.max(0,Math.min(100,d.battery))+'%';$('batteryBar').style.background=d.battery<=15?'#fb7185':d.battery<=30?'#fbbf24':'#34d399';$('distanceResult').textContent=num(d.km)+' km';$('timeResult').textContent=formatTime(route?.duration||0);$('arrivalBattery').textContent=Math.round(d.battery)+'%';$('arrivalFuel').textContent=num(Math.max(0,(Number($('startFuel').value)||0)-d.fuel))+' L';$('costPanel').innerHTML=`<div class="cost-line"><span>Energia elétrica</span><b class="green">${money(d.evCost)}</b></div><div class="cost-line"><span>Gasolina</span><b>${money(d.gasCost)}</b></div><div class="cost-line"><span>Etanol</span><b>${money(d.ethCost)}</b></div><div class="cost-line total"><span>Custo estimado</span><b class="green">${money(d.total)}</b></div><div class="cost-line"><span>Economia vs. gasolina</span><b class="green">${money(d.saving)}</b></div>`;$('summaryGrid').innerHTML=[['Distância',num(d.km)+' km'],['Tempo',formatTime(route?.duration||0)],['Energia',num(d.kwh)+' kWh'],['Custo',money(d.total)],['Bateria chegada',Math.round(d.battery)+'%'],['Combustível usado',num(d.fuel)+' L'],['Economia',money(d.saving)],['Consumo ajustado',num(d.f)+' kWh/100 km']].map(x=>`<div class="summary-item"><span>${x[0]}</span><b>${safe(x[1])}</b></div>`).join('');const badge=$('statusBadge'),box=$('statusBox');if(selectedCar.type==='BEV'&&d.battery<=C.reservePercent){badge.className='status bad';badge.textContent='Recarga necessária';box.className='status-box';box.textContent='⚠️ A bateria estimada chega abaixo da reserva configurada. Planeje uma recarga.'}else{badge.className='status good';badge.textContent='Viagem viável';box.textContent='✅ Estimativa energética dentro dos parâmetros.'}}
function formatTime(sec){const m=Math.round(Number(sec||0)/60),h=Math.floor(m/60),r=m%60;return h?`${h}h ${r}min`:`${r} min`}
function drawRange(){if(rangeLayer){map.removeLayer(rangeLayer);rangeLayer=null}if(!$('showRange').checked||!selectedCar?.range||!waypoints[0]?.coords)return;const pct=Number($('startBattery').value)||0,r=selectedCar.range*pct/100,lat=waypoints[0].coords[0],lng=waypoints[0].coords[1];rangeLayer=L.circle([lat,lng],{radius:r*1000,color:'#34d399',fillColor:'#34d399',fillOpacity:.08,weight:2,dashArray:'6 6'}).addTo(map).bindPopup(`Alcance teórico inicial: ${num(r)} km`)}
function routeDistance(){const cs=route?.geometry?.coordinates||[];let acc=[0];for(let i=1;i<cs.length;i++){acc[i]=acc[i-1]+L.latLng(cs[i-1][1],cs[i-1][0]).distanceTo(L.latLng(cs[i][1],cs[i][0]))/1000}return acc}
function nearest(lat,lng){const cs=route.geometry.coordinates;let best={distance:Infinity,routeKm:0},acc=0;const p=L.latLng(lat,lng);for(let i=1;i<cs.length;i++){const a=L.latLng(cs[i-1][1],cs[i-1][0]),b=L.latLng(cs[i][1],cs[i][0]),seg=a.distanceTo(b)/1000,d=Math.min(p.distanceTo(a),p.distanceTo(b))/1000;if(d<best.distance)best={distance:d,routeKm:acc+Math.min(p.distanceTo(a)/1000,seg)};acc+=seg}return best}
async function loadStations(){stations=[];const unique=new Map();const manual=[[-8.1888,-35.5069,'Planeta Charger - Gravatá','Gravatá / PE',120,'DC'],[-7.3957,-34.9552,'Planeta Charger - Pedras de Fogo','Pedras de Fogo / PB',60,'DC'],[-9.6658,-35.7353,'Eletroposto BR-101 - Maceió','Maceió / AL',50,'DC'],[-10.9472,-37.0731,'Shell Recharge - Aracaju','Aracaju / SE',150,'DC'],[-12.9714,-38.5014,'Eletroposto Salvador','Salvador / BA',150,'DC']];manual.forEach(s=>{const n=nearest(s[0],s[1]);if(n.distance<=C.stationRadiusKm)unique.set(s[0]+s[1],{lat:s[0],lng:s[1],name:s[2],city:s[3],power:s[4],type:s[5],routeKm:n.routeKm})});const cs=route.geometry.coordinates;for(const idx of [0,Math.floor(cs.length/3),Math.floor(cs.length*2/3),cs.length-1]){const c=cs[idx];const q=`[out:json][timeout:12];node["amenity"="charging_station"](${c[1]-.8},${c[0]-.8},${c[1]+.8},${c[0]+.8});out body;`;for(const ep of C.services.overpass){try{const r=await fetch(ep,{method:'POST',body:q});if(!r.ok)continue;const d=await r.json();for(const x of d.elements||[]){if(!x.lat||!x.lon)continue;const n=nearest(x.lat,x.lon);if(n.distance>C.stationRadiusKm)continue;const t=JSON.stringify(x.tags||{}).toLowerCase();unique.set(x.lat.toFixed(4)+x.lon.toFixed(4),{lat:x.lat,lng:x.lon,name:x.tags?.name||x.tags?.operator||'Eletroposto OSM',city:x.tags?.city||x.tags?.town||'Rota',power:/150|120|100/.test(t)?150:50,type:/ccs|dc|kw/.test(t)?'DC':'AC',routeKm:n.routeKm})}break}catch{}}}stations=[...unique.values()].sort((a,b)=>a.routeKm-b.routeKm);renderStations()}
function renderStations(){stationMarkers.forEach(m=>map.removeLayer(m));stationMarkers=[];const visible=stations.filter(s=>(s.type==='DC'&&$('filterDC').checked)||(s.type==='AC'&&$('filterAC').checked));$('stationCount').textContent=visible.length+' encontrados';$('stationsBody').innerHTML=visible.length?visible.map((s,i)=>{const bat=estimateBattery(s.routeKm);const icon=L.divIcon({className:'',html:'<div class="pin">⚡</div>',iconSize:[30,30],iconAnchor:[15,15]});const m=L.marker([s.lat,s.lng],{icon}).addTo(map).bindPopup(`<b>${safe(s.name)}</b><br>${safe(s.city)}<br>${num(s.routeKm)} km · ${s.type} · ${s.power} kW`);stationMarkers.push(m);return `<tr class="station-row"><td>${i+1}</td><td><b>${safe(s.name)}</b></td><td>${safe(s.city)}</td><td>${num(s.routeKm)} km</td><td class="${bat<=15?'text-red-400':'text-emerald-400'}">${Math.round(bat)}%</td><td>${s.type}</td><td>${s.power} kW</td><td><button class="btn secondary" onclick="window.__focusStation(${s.lat},${s.lng})">Ver</button></td></tr>`}).join(''):'<tr><td colspan="8" class="empty">Nenhum eletroposto encontrado com os filtros atuais.</td></tr>'}
window.__focusStation=(lat,lng)=>map.setView([lat,lng],14);
function estimateBattery(km){if(!selectedCar||!['BEV','PHEV','REEV'].includes(selectedCar.type))return 100;const c=(selectedCar._calcConsumption||selectedCar.consumption||0)*factors(),kwh=km*c/100,cap=Number(selectedCar.battery)||0,start=Number($('startBattery').value)||0;return cap?Math.max(0,start-kwh/cap*100):start}
async function loadWeather(){const o=waypoints[0]?.coords;if(!o)return;const box=$('weatherBox');box.classList.remove('hidden');try{const r=await fetch(`${C.services.weather}?latitude=${o[0]}&longitude=${o[1]}&hourly=temperature_2m,precipitation_probability,weathercode&timezone=auto`);const d=await r.json();const date=$('departureDate').value,time=$('departureTime').value||'08:00',target=`${date}T${time.slice(0,2)}:00`,i=Math.max(0,d.hourly.time.findIndex(x=>x>=target)),temp=d.hourly.temperature_2m[i],rain=d.hourly.precipitation_probability[i]||0;box.textContent=`🌡️ ${temp}°C · 🌧️ ${rain}% de probabilidade de chuva`;if(rain>=40&&!$('rainMode').checked){$('rainMode').checked=true;calculateEnergy()}}catch{box.textContent='🌤️ Clima indisponível.'}}
function saveESG(){if(!route||!lastEnergy)return;const gasEq=route.distance/1000/(Number(selectedCar.gasKm)||12),co2=gasEq*C.co2KgPerLiter;esg.trips++;esg.km+=lastEnergy.km;esg.savings+=lastEnergy.saving;esg.co2+=co2;persistESG()}
function persistESG(){localStorage.setItem('evp3_esg',JSON.stringify(esg))}
function renderESG(){$('esgGrid').innerHTML=[['Viagens',esg.trips],['Km planejados',num(esg.km)+' km'],['Economia acumulada',money(esg.savings)],['CO₂ evitado*',num(esg.co2)+' kg']].map(x=>`<div class="summary-item"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}
function exportPDF(){if(!route){toast('Calcule uma viagem antes de exportar.');return}const opt={margin:7,filename:'EV-Planner-Pro-3.0-'+Date.now()+'.pdf',image:{type:'jpeg',quality:.95},html2canvas:{scale:1.5,useCORS:true},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'}};html2pdf().set(opt).from(document.querySelector('.app-shell')).save()}
function exportBackup(){const payload={version:C.version,settings:{battery:$('startBattery').value,fuel:$('startFuel').value,kwh:$('kwhPrice').value,gas:$('gasPrice').value,ethanol:$('ethanolPrice').value},favorites,esg,vehicle:selectedCar};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download='ev-planner-pro-3-backup.json';a.click();URL.revokeObjectURL(a.href)}
function importBackup(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(d.settings){$('startBattery').value=d.settings.battery??$('startBattery').value;$('startFuel').value=d.settings.fuel??$('startFuel').value;$('kwhPrice').value=d.settings.kwh??$('kwhPrice').value;$('gasPrice').value=d.settings.gas??$('gasPrice').value;$('ethanolPrice').value=d.settings.ethanol??$('ethanolPrice').value;saveSettings()}if(Array.isArray(d.favorites)){favorites=d.favorites;localStorage.setItem('evp3_places',JSON.stringify(favorites));renderFavorites()}if(d.esg){esg=d.esg;persistESG();renderESG()}toast('Backup importado.')}catch{toast('Arquivo de backup inválido.')}};r.readAsText(f)}
function copySummary(){if(!lastEnergy){toast('Calcule uma viagem primeiro.');return}const t=`EV Planner Pro 3.0\nVeículo: ${selectedCar.brand} ${selectedCar.model} ${selectedCar.version||''}\nDistância: ${num(lastEnergy.km)} km\nTempo: ${formatTime(route.duration)}\nEnergia: ${num(lastEnergy.kwh)} kWh\nBateria chegada: ${Math.round(lastEnergy.battery)}%\nCusto: ${money(lastEnergy.total)}\nEconomia: ${money(lastEnergy.saving)}`;navigator.clipboard?.writeText(t).then(()=>toast('Resumo copiado.')).catch(()=>toast('Não foi possível copiar automaticamente.'))}
window.addEventListener('load',init);
})();
