window.EV_CONFIG = {
  version: '3.9.2',
  versionHistory: [
    {version:'3.9.2',date:'25/08/2026',description:'Revisão completa da autonomia de híbridos: a rota agora soma a autonomia elétrica disponível e a autonomia de combustível informada, permitindo que a bateria chegue a 0% e a combustão assuma o restante. O plano informa o km aproximado em que termina a autonomia elétrica e quantos km de combustível ainda restam.'},
    {version:'3.9.1',date:'25/08/2026',description:'Correção da validação do plano inteligente: a recomendação de recarga agora usa a bateria/combustível realmente estimados na chegada; híbridos exibem automaticamente o campo de litros e combinam autonomia elétrica e combustão de forma consistente.'},
    {version:'3.9.0',date:'25/08/2026',description:'Revisão geral dos cálculos de viagem: autonomia elétrica baseada no INMETRO/PBEV, combinação correta de energia elétrica + combustível para veículos híbridos, entrada de litros iniciais e tratamento mais conservador quando não há consumo de combustível confiável.'},
    {version:'3.8.4',date:'25/08/2026',description:'Híbridos passam a combinar a autonomia elétrica disponível com os litros de combustível informados pelo usuário, calculando autonomia total, combustível necessário, eventual déficit e combustível estimado na chegada.'},
    {version:'3.8.3',date:'24/08/2026',description:'Correção da estratégia da volta: elimina a referência inexistente returnText e gera uma recomendação segura de parada/recarga com base nos carregadores compatíveis encontrados.'},
    {version:'3.8.2',date:'24/08/2026',description:'Eletropostos também mapeados na rota de volta e estratégia inteligente de parada/recarga para a volta, mantendo a bateria acima da reserva de segurança.'},
    {version:'3.8.1',date:'24/08/2026',description:'Correção do cálculo energético da rota de ida e volta e carregamento confiável do segundo mapa da volta.'},
    {version:'3.8',date:'24/08/2026',description:'Ida e volta com data e horário independentes para o retorno e dois mapas separados: ida e volta, mantendo a coloração energética e a rota de retorno em azul.'},
    {version:'3.7',date:'24/08/2026',description:'Versão única no topo, autonomia INMETRO + referência do painel, horário de retorno, rota de volta em azul com lógica energética própria e estratégia automática de parada por nível de bateria.'},
    {version:'3.6',date:'24/08/2026',description:'Dados de autonomia priorizando INMETRO/PBEV, compatibilidade real de recarga por veículo (AC/DC), bloqueio de carregadores incompatíveis e rastreabilidade da fonte dos dados.'},
    {version:'3.5',date:'24/08/2026',description:'Distribuição inteligente de eletropostos ao longo de toda a rota, busca reforçada no trecho final/destino e versão centralizada em uma única fonte.'},
    {version:'3.4',date:'24/08/2026',description:'Planejamento inteligente: viabilidade, paradas recomendadas, custo/tempo, nível de segurança, rota colorida por energia/combustível e pontos de abastecimento.'},
    {version:'3.3',date:'24/08/2026',description:'Performance aprimorada, cache inteligente de buscas, rotas recentes, validação, gerenciamento de pontos manuais, filtros de carregamento e atualização do PWA.'},
    {version:'3.2',date:'23/08/2026',description:'Favoritos de veículo e rota, escolha de origem/destino, resumo detalhado, busca de pontos no mapa, otimização de desempenho e interface mobile mais compacta.'},
    {version:'3.1',date:'23/08/2026',description:'Logo da aplicação, bateria 0–100%, combustível condicional, busca ampliada de eletropostos, cadastro manual e mensagem de cálculo concluído.'},
    {version:'3.0',date:'23/08/2026',description:'Nova base do EV Planner Pro com planejamento de rotas, energia, custos, mapa, eletropostos, PDF, backup e PWA.'}
  ],
  reservePercent: 15,
  stopBatteryPercent: 20,
  stationRadiusKm: 18,
  stationWideRadiusKm: 40,
  stationSamplePoints: 18,
  stationDestinationSamplePoints: 7,
  stationDestinationRadiusKm: 28,
  fuelSamplePoints: 8,
  geocodeDebounce: 350,
  requestTimeoutMs: 9000,
  routeCacheTtlMs: 15*60*1000,
  stationCacheTtlMs: 30*60*1000,
  dataPolicy: {rangeSource:'INMETRO_PBEV', rangeFallback:false, currentCycle:'PBEV 2026 - 18º ciclo', currentCycleDate:'19/08/2026', sourceUrl:'https://www.gov.br/inmetro/pt-br/assuntos/regulamentacao/avaliacao-da-conformidade/programa-brasileiro-de-etiquetagem/tabelas-de-eficiencia-energetica/veiculos-automotivos-pbe-veicular'},
  fuelCacheTtlMs: 30*60*1000,
  recentTripsLimit: 8,
  co2KgPerLiter: 2.31,
  defaults: { kwhPrice: 0.75, gasPrice: 6.88, ethanolPrice: 5.07, startBattery: 80, startFuel: 40 },
  services: {
    geocode: 'https://photon.komoot.io/api/',
    route: 'https://router.project-osrm.org/route/v1/driving/',
    weather: 'https://api.open-meteo.com/v1/forecast',
    overpass: ['https://overpass-api.de/api/interpreter','https://overpass.private.coffee/api/interpreter']
  }
};
