window.EV_VEHICLES = [
  {
    "brand": "BYD",
    "model": "Dolphin Mini",
    "version": "EV",
    "type": "BEV",
    "engine": "",
    "power": "75 cv",
    "battery": 38.0,
    "range": 281.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "BYD",
    "model": "Dolphin",
    "version": "GS",
    "type": "BEV",
    "engine": "",
    "power": "95 cv",
    "battery": 44.9,
    "range": 292.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "BYD",
    "model": "Dolphin",
    "version": "Plus",
    "type": "BEV",
    "engine": "",
    "power": "204 cv",
    "battery": 60.4,
    "range": 429.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "BYD",
    "model": "Yuan Pro",
    "version": "EV",
    "type": "BEV",
    "engine": "",
    "power": "177 cv",
    "battery": 45.1,
    "range": 320.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "BYD",
    "model": "Seal",
    "version": "EV",
    "type": "BEV",
    "engine": "",
    "power": "531 cv",
    "battery": 82.5,
    "range": 372.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "AWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "BYD",
    "model": "Sealion 7",
    "version": "EV",
    "type": "BEV",
    "engine": "",
    "power": "530 cv",
    "battery": 82.56,
    "range": 500.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "AWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "BYD",
    "model": "Tan",
    "version": "EV",
    "type": "BEV",
    "engine": "",
    "power": "517 cv",
    "battery": 108.8,
    "range": 435.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "AWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "BYD",
    "model": "King",
    "version": "GL",
    "type": "PHEV",
    "engine": "",
    "power": "209 cv",
    "battery": null,
    "range": 80.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "BYD",
    "model": "King",
    "version": "GS",
    "type": "PHEV",
    "engine": "",
    "power": "235 cv",
    "battery": null,
    "range": 80.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "BYD",
    "model": "Song Pro",
    "version": "GL",
    "type": "PHEV Flex",
    "engine": "",
    "power": "",
    "battery": null,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "BYD",
    "model": "Song Pro",
    "version": "GS",
    "type": "PHEV Flex",
    "engine": "",
    "power": "219 cv",
    "battery": null,
    "range": 72.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "BYD",
    "model": "Song Plus",
    "version": "DM-i",
    "type": "PHEV",
    "engine": "",
    "power": "245 cv",
    "battery": null,
    "range": 110.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "BYD",
    "model": "Song Plus Premium",
    "version": "DM-i",
    "type": "PHEV",
    "engine": "",
    "power": "324 cv",
    "battery": 26.6,
    "range": 87.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "AWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "BYD",
    "model": "Shark",
    "version": "GS",
    "type": "PHEV",
    "engine": "",
    "power": "437 cv",
    "battery": null,
    "range": 100.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "AWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "Leapmotor",
    "model": "B10",
    "version": "BEV",
    "type": "BEV",
    "engine": "",
    "power": "218 cv",
    "battery": 56.2,
    "range": 288.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "Leapmotor",
    "model": "C10",
    "version": "Elétrico",
    "type": "BEV",
    "engine": "",
    "power": "218 cv",
    "battery": 69.9,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "Leapmotor",
    "model": "C10",
    "version": "Ultra-Híbrido",
    "type": "REEV",
    "engine": "1.5 gerador",
    "power": "215 cv",
    "battery": 28.4,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "RWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "Geely",
    "model": "EX2",
    "version": "Pro",
    "type": "BEV",
    "engine": "",
    "power": "116 cv",
    "battery": 39.4,
    "range": 288.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "Geely",
    "model": "EX2",
    "version": "Max",
    "type": "BEV",
    "engine": "",
    "power": "116 cv",
    "battery": 39.4,
    "range": 288.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "Geely",
    "model": "EX5",
    "version": "Pro",
    "type": "BEV",
    "engine": "",
    "power": "218 cv",
    "battery": 60.22,
    "range": 400.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "Geely",
    "model": "EX5",
    "version": "Max",
    "type": "BEV",
    "engine": "",
    "power": "218 cv",
    "battery": 60.22,
    "range": 400.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "Geely",
    "model": "EX5 EM-i",
    "version": "Pro",
    "type": "PHEV",
    "engine": "",
    "power": "262 cv",
    "battery": 18.4,
    "range": 65.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "Geely",
    "model": "EX5 EM-i",
    "version": "Max",
    "type": "PHEV",
    "engine": "",
    "power": "262 cv",
    "battery": 18.4,
    "range": 65.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "Geely",
    "model": "EX5 EM-i",
    "version": "Ultra",
    "type": "PHEV",
    "engine": "",
    "power": "262 cv",
    "battery": 29.8,
    "range": 112.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "GWM",
    "model": "Ora 03",
    "version": "Skin",
    "type": "BEV",
    "engine": "",
    "power": "171 cv",
    "battery": 48.0,
    "range": 312.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "GWM",
    "model": "Ora 03",
    "version": "BEV58",
    "type": "BEV",
    "engine": "",
    "power": "171 cv",
    "battery": 58.0,
    "range": 315.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "GWM",
    "model": "Ora 03",
    "version": "GT",
    "type": "BEV",
    "engine": "",
    "power": "171 cv",
    "battery": 63.0,
    "range": 397.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "GWM",
    "model": "Haval H6",
    "version": "HEV ONE",
    "type": "HEV",
    "engine": "",
    "power": "243 cv",
    "battery": null,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "GWM",
    "model": "Haval H6",
    "version": "HEV2",
    "type": "HEV",
    "engine": "",
    "power": "243 cv",
    "battery": null,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "GWM",
    "model": "Haval H6",
    "version": "PHEV19",
    "type": "PHEV",
    "engine": "",
    "power": "326 cv",
    "battery": null,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "AWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "GWM",
    "model": "Haval H6",
    "version": "PHEV35",
    "type": "PHEV",
    "engine": "",
    "power": "393 cv",
    "battery": null,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "AWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "GWM",
    "model": "Haval H6 GT",
    "version": "PHEV",
    "type": "PHEV",
    "engine": "",
    "power": "393 cv",
    "battery": null,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "AWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "GWM",
    "model": "Tank 300",
    "version": "PHEV",
    "type": "PHEV",
    "engine": "",
    "power": "394 cv",
    "battery": null,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "AWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "GAC/AION",
    "model": "Aion UT",
    "version": "Premium",
    "type": "BEV",
    "engine": "",
    "power": "204 cv",
    "battery": 44.12,
    "range": 253.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "GAC/AION",
    "model": "Aion UT",
    "version": "Elite",
    "type": "BEV",
    "engine": "",
    "power": "204 cv",
    "battery": 60.0,
    "range": 310.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "GAC/AION",
    "model": "Aion ES",
    "version": "Plus",
    "type": "BEV",
    "engine": "",
    "power": "136 cv",
    "battery": 55.2,
    "range": 314.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "GAC/AION",
    "model": "Aion Y",
    "version": "Premium",
    "type": "BEV",
    "engine": "",
    "power": "204 cv",
    "battery": 63.2,
    "range": 316.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "GAC/AION",
    "model": "Aion V",
    "version": "Elite",
    "type": "BEV",
    "engine": "",
    "power": "204 cv",
    "battery": 75.3,
    "range": 392.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "GAC/AION",
    "model": "Hyptec HT",
    "version": "Elite",
    "type": "BEV",
    "engine": "",
    "power": "245 cv",
    "battery": 72.7,
    "range": 362.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "RWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "OMODA",
    "model": "Omoda 5",
    "version": "HEV Luxury",
    "type": "HEV",
    "engine": "",
    "power": "235 cv",
    "battery": 1.83,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "OMODA",
    "model": "Omoda 5",
    "version": "HEV Prestige",
    "type": "HEV",
    "engine": "",
    "power": "235 cv",
    "battery": 1.83,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "JAECOO",
    "model": "Jaecoo 7",
    "version": "SHS Prestige",
    "type": "PHEV",
    "engine": "",
    "power": "339 cv",
    "battery": 18.3,
    "range": 79.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "CAOA Chery",
    "model": "Tiggo 5X",
    "version": "Pro Max Drive",
    "type": "HEV",
    "engine": "",
    "power": "não informado",
    "battery": null,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "CAOA Chery",
    "model": "Tiggo 7",
    "version": "Pro Hybrid Max Drive",
    "type": "HEV",
    "engine": "",
    "power": "157 cv",
    "battery": null,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "FIAT",
    "model": "Pulse",
    "version": "Audace Hybrid",
    "type": "MHEV",
    "engine": "",
    "power": "125 cv",
    "battery": null,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "FIAT",
    "model": "Pulse",
    "version": "Impetus Hybrid",
    "type": "MHEV",
    "engine": "",
    "power": "125 cv",
    "battery": null,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "FIAT",
    "model": "Fastback",
    "version": "Audace Hybrid",
    "type": "MHEV",
    "engine": "",
    "power": "125 cv",
    "battery": null,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "FIAT",
    "model": "Fastback",
    "version": "Impetus Hybrid",
    "type": "MHEV",
    "engine": "",
    "power": "125 cv",
    "battery": null,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "TOYOTA",
    "model": "Corolla",
    "version": "Hybrid",
    "type": "HEV",
    "engine": "",
    "power": "não informado",
    "battery": null,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "TOYOTA",
    "model": "Corolla Cross",
    "version": "XRX Hybrid",
    "type": "HEV",
    "engine": "",
    "power": "101 cv*",
    "battery": null,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "TOYOTA",
    "model": "RAV4",
    "version": "SX Connect",
    "type": "HEV",
    "engine": "",
    "power": "222 cv",
    "battery": null,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "AWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "TOYOTA",
    "model": "RAV4",
    "version": "XSE",
    "type": "PHEV",
    "engine": "",
    "power": "306 cv",
    "battery": null,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "AWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "TOYOTA",
    "model": "bZ4X",
    "version": "AWD",
    "type": "BEV",
    "engine": "",
    "power": "343 cv",
    "battery": 73.1,
    "range": 361.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "AWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "HONDA",
    "model": "Civic",
    "version": "Advanced Hybrid",
    "type": "HEV",
    "engine": "",
    "power": "não informado",
    "battery": 1.0,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "HONDA",
    "model": "Accord",
    "version": "Advanced Hybrid",
    "type": "HEV",
    "engine": "",
    "power": "204 cv",
    "battery": 1.05,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "HONDA",
    "model": "CR-V",
    "version": "Advanced Hybrid",
    "type": "HEV",
    "engine": "",
    "power": "não informado",
    "battery": null,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "AWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "HYUNDAI",
    "model": "Kona",
    "version": "Hybrid Ultimate",
    "type": "HEV",
    "engine": "",
    "power": "141 cv",
    "battery": 1.32,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "HYUNDAI",
    "model": "Kona",
    "version": "Hybrid Signature",
    "type": "HEV",
    "engine": "",
    "power": "141 cv",
    "battery": 1.32,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "HYUNDAI",
    "model": "Ioniq 5",
    "version": "—",
    "type": "BEV",
    "engine": "",
    "power": "325 cv",
    "battery": 84.0,
    "range": 374.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "AWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "KIA",
    "model": "Niro",
    "version": "EX",
    "type": "HEV",
    "engine": "",
    "power": "141 cv",
    "battery": null,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "KIA",
    "model": "Niro",
    "version": "SX",
    "type": "HEV",
    "engine": "",
    "power": "141 cv",
    "battery": null,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "KIA",
    "model": "EV5",
    "version": "Land",
    "type": "BEV",
    "engine": "",
    "power": "217 cv",
    "battery": 88.16,
    "range": 406.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "KIA",
    "model": "EV9",
    "version": "GTL",
    "type": "BEV",
    "engine": "",
    "power": "384 cv",
    "battery": 99.0,
    "range": 436.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "AWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "MG",
    "model": "MG4",
    "version": "Urban Comfort",
    "type": "BEV",
    "engine": "",
    "power": "150 cv",
    "battery": 43.0,
    "range": 299.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "RWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "MG",
    "model": "MG4",
    "version": "Urban Luxury",
    "type": "BEV",
    "engine": "",
    "power": "150 cv",
    "battery": 43.0,
    "range": 299.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "RWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "MG",
    "model": "MG4",
    "version": "Urban Luxury",
    "type": "BEV",
    "engine": "",
    "power": "160 cv",
    "battery": 54.0,
    "range": 358.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "RWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "MG",
    "model": "MG4",
    "version": "Luxury",
    "type": "BEV",
    "engine": "",
    "power": "204 cv",
    "battery": 64.0,
    "range": 364.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "RWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "RENAULT",
    "model": "Kwid E-Tech",
    "version": "E-Tech",
    "type": "BEV",
    "engine": "",
    "power": "65 cv",
    "battery": 26.8,
    "range": 180.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "RENAULT",
    "model": "Megane E-Tech",
    "version": "E-Tech",
    "type": "BEV",
    "engine": "",
    "power": "218 cv",
    "battery": 60.0,
    "range": 248.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "VOLVO",
    "model": "EX30",
    "version": "Plus",
    "type": "BEV",
    "engine": "",
    "power": "272 cv",
    "battery": 51.0,
    "range": 250.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "RWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "VOLVO",
    "model": "EX30",
    "version": "Ultra Twin Motor",
    "type": "BEV",
    "engine": "",
    "power": "428 cv",
    "battery": 69.0,
    "range": 316.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "AWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "VOLVO",
    "model": "EX30",
    "version": "Cross Country",
    "type": "BEV",
    "engine": "",
    "power": "428 cv",
    "battery": 69.0,
    "range": 327.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "AWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "CHEVROLET",
    "model": "Spark EUV",
    "version": "41,9 kWh",
    "type": "BEV",
    "engine": "",
    "power": "102 cv",
    "battery": 41.9,
    "range": 260.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "CHEVROLET",
    "model": "Equinox EV",
    "version": "85 kWh",
    "type": "BEV",
    "engine": "",
    "power": "292 cv",
    "battery": 85.0,
    "range": 442.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "SUZUKI",
    "model": "e-Vitara",
    "version": "—",
    "type": "BEV",
    "engine": "",
    "power": "184 cv",
    "battery": 61.0,
    "range": 293.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "AWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "JETOUR",
    "model": "T1",
    "version": "PHEV",
    "type": "PHEV",
    "engine": "",
    "power": "315 cv",
    "battery": 26.7,
    "range": 88.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "AWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "JETOUR",
    "model": "T2",
    "version": "PHEV",
    "type": "PHEV",
    "engine": "",
    "power": "339 cv",
    "battery": 26.7,
    "range": 75.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "AWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "DENZA",
    "model": "B5",
    "version": "—",
    "type": "PHEV",
    "engine": "",
    "power": "677 cv",
    "battery": 31.8,
    "range": 74.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "AWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "DENZA",
    "model": "Z9 GT",
    "version": "—",
    "type": "BEV",
    "engine": "",
    "power": "965 cv",
    "battery": 100.0,
    "range": 440.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "AWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "AVATR",
    "model": "11",
    "version": "5 lugares",
    "type": "BEV",
    "engine": "",
    "power": "585 cv",
    "battery": 116.0,
    "range": 550.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "AWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "AVATR",
    "model": "11",
    "version": "4 lugares",
    "type": "BEV",
    "engine": "",
    "power": "585 cv",
    "battery": 116.0,
    "range": 550.0,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "AWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "LEXUS",
    "model": "ES",
    "version": "350h",
    "type": "HEV",
    "engine": "",
    "power": "247 cv",
    "battery": 251.6,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "PEUGEOT",
    "model": "e-2008",
    "version": "—",
    "type": "BEV",
    "engine": "",
    "power": "não informado",
    "battery": null,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "PEUGEOT",
    "model": "e-208",
    "version": "—",
    "type": "BEV",
    "engine": "",
    "power": "não informado",
    "battery": null,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  },
  {
    "brand": "PEUGEOT",
    "model": "e-Expert",
    "version": "—",
    "type": "BEV",
    "engine": "",
    "power": "não informado",
    "battery": null,
    "range": null,
    "totalRange": null,
    "consumption": null,
    "fuelConsumption": "",
    "traction": "FWD",
    "zero100": "",
    "price": ""
  }
];
